# For detailed configuration options and explanations, please refer to docs/configuration.md
# Example: https://github.com/someuser/someproject/blob/main/docs/configuration.md

email:
  from: viktor@farcic.com
  thumbnailTo: viktor@farcic.com
  editTo: viktor@farcic.com
  financeTo: devopstoolkit@acme.com
ai:
  provider: anthropic  # Options: azure, anthropic
  azure:
    endpoint: https://dotaisweden.openai.azure.com
    deployment: gpt-4-1106-preview
    # apiVersion: 2023-05-15  # Optional, defaults to 2023-05-15
  anthropic:
    model: claude-sonnet-4-5-20250929  # Latest Claude Sonnet 4.5 model
    # key: set via ANTHROPIC_API_KEY environment variable
hugo:
  path: ../devopstoolkit-live/
youtube:
  channelId: UCfz8x0lVzJpb_dgWm9kPVrw
bluesky:
  identifier: vfarcic.bsky.social
  url: https://bsky.social/xrpc
# Added for PRD: Automated Video Language Setting
videoDefaults:
  language: "en"
  audioLanguage: "en"

# Added for PRD: REST API Configuration
api:
  port: 8080
  enabled: false

slack:
  targetChannelIDs:
    - "C0123EXAMPLE1" # Placeholder: e.g., #announcements
    - "C0456EXAMPLE2" # Placeholder: e.g., #new-videos